
@token = 7e81605
#@server=http://localhost:3000
@server=http://5.178.85.184:3000

#### posts
GET {{server}}/posts
X-Auth: {{token}}


### get post 
GET {{server}}/post/1
X-Auth: {{token}}

### update post
PUT {{server}}/post/1
content-type: application/json

{
  "title": "hic tempore officiis consequuntur ab!!!!!!",
  "body": "Quaerat facere nesciunt similique optio.\nSed fugiat et amet sit molestiae quibusdam voluptas dolorem perspiciatis.\nTenetur repellendus recusandae voluptatibus qui quisquam quidem.\nVel vero est.\nConsequatur qui voluptatem sed."
}

### new post
POST {{server}}/post
X-Auth: {{token}}
content-type: application/json

{
  "title": "Zagolovok",
  "body": "Quaerat facere."
}

### login
POST {{server}}/login
content-type: application/json

{
    "username": "megas",
    "password": "q1w2e3"
}

### test
GET {{server}}:3000/
X-Auth: {{token}}
